name: Deploy to Dev Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PEM_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Run deployment script over SSH
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SERVER_ADDRESS }}
            username: ${{ secrets.SERVER_USER }}
            key_path: deploy_key.pem
            script_stop: true
            script: |
              sudo -u root bash -c '
              cd /usr/homework/vue-shop
              git pull origin dev
              npm install
              npm run build
              # node server.js &
              nohup node server.js > /dev/null 2>&1 &
              echo "Server started in background"
              exit 0'
    
      - name: Cleanup
        run: rm -f deploy_key.pem
